### ISSUE TITLE
XSS Não stored

### ISSUE THREAD

**Issue by LuccaPrado** [Cv-Keep/cvkeep-frontend#2]
Opa, dei uma olhadinha e nos campos como o de apresentação está tratando tags ao digitar (imagino que está pegando a cada input) porém, se der ctrl c e ctrl v, ele chega a executar tags... Talvez seja interessante travar para só permitir alfanuméricos. 

Base:
https://www.stackhawk.com/blog/vue-xss-guide-examples-and-prevention/#exploring-the-vulnerability

exemplo usado:
<img 
  src="https://jnx.me/img/profile.jpg" 
  style="display:none" 
  onload="alert('ish')"
>

**Comment by felippe-regazio** [comment]
Cara, obrigadão por reportar essa issue, foi bem importante de se corrigir.

---

Done on commit: https://github.com/Cv-Keep/cvkeep-frontend/commit/8d54c4546efdb5c19224ea0c443e9918f0bdd058
Waiting Deploy
