### ISSUE TITLE
Predefined values in profile

### ISSUE THREAD

**Issue by brunoocasali** [Cv-Keep/cvkeep-frontend#3]
When you start to update your profile, you see a predefined value in country/city etc...

![image](https://user-images.githubusercontent.com/4116980/137778668-64844549-bdf6-4a2c-90bb-4c35100e165c.png)

What do you think to use placeholders instead?

**Comment by felippe-regazio** [comment]
Done

front commit: https://github.com/Cv-Keep/cvkeep-frontend/commit/374434ffa43c26e349be3f53706231426f23e36e
back commit: https://github.com/Cv-Keep/cvkeep-backend/commit/2544e7b962cf42502d999d5201e8f55aff211513

Waiting deploy
