### ISSUE TITLE
Nome de usuário

### ISSUE THREAD

**Issue by victorhenrique07** [Cv-Keep/cvkeep-frontend#4]
Sempre que dou espaço para por meu sobrenome o cursor volta para o começo da linha
![image](https://user-images.githubusercontent.com/61640711/137779694-9917ff3b-a591-40f7-8a22-d7318f54a902.png)

**Comment by felippe-regazio** [comment]
Fixed on commit: https://github.com/Cv-Keep/cvkeep-frontend/commit/cceea10847e1d9d0b394abc44a3c42aff21c469b
Aguardando deploy
