### ISSUE TITLE
CV export should have an "in progress" indicator

### ISSUE THREAD

**Issue by rgsilva** [Cv-Keep/cvkeep-frontend#44]
I tested the PDF and PNG export features and realized I had no visible feedback it was working in the background. The user should have some kind of in progress/loading/exporting indicator while everything gets loaded and the file is generated. The main reason is because, due to the (quite numerous) amount of resource requests during the generation, the process can take a few seconds, even more if such resources are not cached and/or the user is on a slower connection.

**Comment by felippe-regazio** [comment]
fair enough. roadmap of the task:

- add a full screen loading spinner while generating the cv pdf or png
- the loading indicator must show a message "Generating CV [pdf, png], please wait..."
- add the proper i18n or open a new issue to translate the task

**Comment by ravilock** [comment]
Hi. Since this issue was not solved since Nov 14, may I solve it?

**Comment by felippe-regazio** [comment]
sorry @ravilock just saw your comment now. my bad. anyway, the issue has been solved on:

https://github.com/Cv-Keep/cvkeep-frontend/commit/86b4c2fc0a76f91908a565054a89b790736e614f
