### ISSUE TITLE
How save I my dates

### ISSUE THREAD

**Issue by LorenaPassagem** [Cv-Keep/cvkeep-frontend#46]
![image](https://user-images.githubusercontent.com/28634203/143088276-a843a7f7-b94c-4824-84dd-199ca09a541d.png)
When I scrolled there is no how saved and reload the page my information wasn't saved. :)

**Comment by LorenaPassagem** [comment]
👀 my pic was saved.

**Comment by felippe-regazio** [comment]
Hello Lorena. There is a "Save" Button on the left side menu. You just click it and your data will be saved. 
To send your CV to someone just send the URL (as a profile). If you want to download your CV, go to settings.

![image](https://user-images.githubusercontent.com/31618881/143174101-14c96f1b-5636-4757-ab31-70b20e38b2b4.png)
