### ISSUE TITLE
Correção ortografia e-mail

### ISSUE THREAD

**Issue by elitonk** [Cv-Keep/cvkeep-frontend#47]
Nos e-mails recebidos aos novos usuários contém pequenos erros, tais como na [imagem](https://i.nuuls.com/6iIvs.png)

**Comment by elitonk** [comment]
![Screenshot_4439](https://user-images.githubusercontent.com/73960969/153686075-39350ffc-d1e0-4679-a706-c9810e67f0e1.png)
agora que vi que tinha integrado a função da imagem 👍🏾

**Comment by felippe-regazio** [comment]
done on:

fix raw text e-mail typo:
https://github.com/Cv-Keep/cvkeep-backend/commit/2076649d9ed99717d36ec14699adbad03045b28c

fix html e-mail typo:
https://github.com/Cv-Keep/cvkeep-backend/commit/940cce1a7b4c53e352bf8d4a884276f0c0e22871
