### ISSUE TITLE
CVs should have an 'email' field on it's contacts form, specially when exported.

### ISSUE THREAD

**Issue by ravilock** [Cv-Keep/cvkeep-frontend#48]
After exporting my CV to PDF I noticed that there wasn't any "email" field on it.
We have a phone number contact, but usually, the main form of communication when hiring or applying for a job is e-mail.
Maybe we should leave the email address at the top of exported CVs with the other means of contact?

**Comment by felippe-regazio** [comment]
Done, now you must see a "Public e-mail" field on your CV Header, in case you want to add a public e-mail to the header. Also, this e-mail will be automatic filled with the login e-mail on the very first Cv Keep Login.

![image](https://user-images.githubusercontent.com/31618881/153734886-7e1f0aad-cea7-418f-aa1d-ec0a5d547412.png)

![image](https://user-images.githubusercontent.com/31618881/153734948-568dc041-0a46-4f01-9ec6-fa237b88ef7b.png)

**Comment by ravilock** [comment]
nice!

**Comment by ravilock** [comment]
I'm already using it!
