### ISSUE TITLE
Colaboração com testes e2e - CV KEEP

### ISSUE THREAD

**Issue by santosvini** [Cv-Keep/cvkeep-frontend#52]
Boa Noite Felipe, blz?

Gostaria de contribuir com seu projeto com testes automatizados!

Abs

**Comment by felippe-regazio** [comment]
Opa, fique a vontade pra subir os PRs hahaha

**Comment by santosvini** [comment]
Fala Felipe, perdão acabei esquecendo de responder, mas acredito que nada no momento, por enquanto farei os e2e e posteriormente de API se for o caso, farei o fork e instalar as dependencias e frame de automação
