### ISSUE TITLE
Perda de informações em caso de misclick

### ISSUE THREAD

**Issue by sandralcouto** [Cv-Keep/cvkeep-frontend#9]
![image](https://user-images.githubusercontent.com/67126114/137901733-ec9ba825-fc5d-4dc3-be3a-3859d4bb382b.png)

Quando abro e preencho essa tela com algumas informações, se acidentalmente eu clicar para fora do quadro de informações básicas perco as informações que já digitei

**Comment by felippe-regazio** [comment]
Resolvido: https://github.com/Cv-Keep/cvkeep-frontend/commit/6376fffe9891887497b00f6d9ae7aac4ec9454c0

Ao invés da lightbox fechar, caso haja um click na backdrop, o conteudo (whitebox) vai tremer chamando a atenção do/a usuário/a.

Aguardando deploy.
